import { map } from 'rxjs';
import { humanize } from '../../../core/utils/format';
import { AdminModel, Lookups, Option, RoleRow } from '../data/admin.models';
import { CrudConfig, CrudCtx, Row } from '../shared/crud.types';

/* ---------- option helpers ---------- */

const yesNo = (label: string, key = 'status'): { key: string; label: string; options: Option[] } => ({
  key,
  label,
  options: [{ value: 'active', label: 'Active' }, { value: 'inactive', label: 'Inactive' }],
});

export function categoryOptions(lk: Lookups | null): Option<number>[] {
  const cats = lk?.categories ?? [];
  const byId = new Map(cats.map((c) => [c.id, c]));
  return cats
    .map((c) => {
      const parent = c.parent_id ? byId.get(c.parent_id) : null;
      return { value: c.id, label: parent ? `${parent.name} › ${c.name}` : c.name };
    })
    .sort((a, b) => a.label.localeCompare(b.label));
}

const brandOptions = (ctx: CrudCtx): Option[] => (ctx.lookups?.brands ?? []).map((b) => ({ value: b.id, label: b.name }));
const manufacturerOptions = (ctx: CrudCtx): Option[] => (ctx.lookups?.manufacturers ?? []).map((m) => ({ value: m.id, label: m.name, group: humanize(m.vehicle_type) }));
const vehicleTypes: Option[] = [{ value: 'car', label: 'Car' }, { value: 'motorcycle', label: 'Motorcycle' }];

const json = (v: unknown) => (v ? JSON.stringify(v, null, 2) : '—');

/* ---------- configs ---------- */

export const CRUD_CONFIGS: Record<string, CrudConfig> = {
  categories: {
    key: 'categories',
    title: 'Categories',
    subtitle: 'Organise the catalogue. Sub-categories inherit filters from their parent.',
    singular: 'Category',
    resource: 'categories',
    multipart: true,
    toggle: 'is_active',
    refreshesLookups: true,
    rowTitle: (r) => r['name'],
    search: 'Search categories…',
    filters: [{ key: 'parent_id', label: 'Levels', options: [{ value: 'root', label: 'Top-level only' }] }],
    columns: [
      { key: 'image', label: '', type: 'image' },
      { key: 'name', label: 'Name', type: 'strong', sub: (r) => (r['parent'] ? `in ${r['parent'].name}` : 'Top level') },
      { key: 'vehicle_type', label: 'For', value: (r) => humanize(r['vehicle_type'] ?? 'universal'), hideMobile: true },
      { key: 'products_count', label: 'Products', type: 'number', align: 'right' },
      { key: 'is_featured', label: 'Featured', type: 'bool', hideMobile: true },
      { key: 'sort_order', label: 'Order', type: 'number', align: 'right', hideMobile: true },
      { key: 'is_active', label: 'Active', type: 'toggle' },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, maxLength: 120 },
      { key: 'slug', label: 'Slug', type: 'text', maxLength: 140, hint: 'Leave blank to generate from the name.', pattern: /^[a-z0-9-_]+$/, patternMessage: 'Lowercase letters, numbers and dashes only.' },
      { key: 'parent_id', label: 'Parent category', type: 'select', placeholder: '— None (top level) —', options: (ctx, v) => categoryOptions(ctx.lookups).filter((o) => o.value !== v['id']) },
      { key: 'vehicle_type', label: 'Vehicle type', type: 'select', placeholder: 'Universal', options: [...vehicleTypes, { value: 'universal', label: 'Universal' }] },
      { key: 'icon', label: 'Icon name', type: 'text', maxLength: 60, placeholder: 'e.g. wrench' },
      { key: 'sort_order', label: 'Sort order', type: 'number', min: 0, default: 0 },
      { key: 'description', label: 'Description', type: 'textarea', maxLength: 2000 },
      { key: 'image', label: 'Image', type: 'image', imageKey: 'image', removeKey: 'remove_image' },
      { key: 'seo_title', label: 'SEO title', type: 'text', maxLength: 190 },
      { key: 'seo_description', label: 'SEO description', type: 'text', maxLength: 500 },
      { key: 'is_active', label: 'Active (visible in store)', type: 'checkbox', default: true },
      { key: 'is_featured', label: 'Featured on homepage', type: 'checkbox' },
    ],
    fromRow: (r) => ({ ...r }),
    deleteMessage: (r) => `“${r['name']}” will be removed. Categories that still contain products or sub-categories cannot be deleted.`,
  },

  brands: {
    key: 'brands',
    title: 'Brands',
    subtitle: 'Manufacturers of the parts you sell.',
    singular: 'Brand',
    resource: 'brands',
    multipart: true,
    toggle: 'is_active',
    refreshesLookups: true,
    rowTitle: (r) => r['name'],
    filters: [yesNo('Statuses')],
    columns: [
      { key: 'logo', label: '', type: 'image' },
      { key: 'name', label: 'Brand', type: 'strong', sub: (r) => r['country'] },
      { key: 'products_count', label: 'Products', type: 'number', align: 'right' },
      { key: 'website', label: 'Website', hideMobile: true },
      { key: 'is_featured', label: 'Featured', type: 'bool', hideMobile: true },
      { key: 'is_active', label: 'Active', type: 'toggle' },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, maxLength: 120 },
      { key: 'slug', label: 'Slug', type: 'text', maxLength: 140, hint: 'Leave blank to generate from the name.' },
      { key: 'country', label: 'Country', type: 'text', maxLength: 60 },
      { key: 'website', label: 'Website', type: 'url', maxLength: 255, placeholder: 'https://' },
      { key: 'sort_order', label: 'Sort order', type: 'number', min: 0, default: 0 },
      { key: 'description', label: 'Description', type: 'textarea', maxLength: 2000 },
      { key: 'logo', label: 'Logo', type: 'image', imageKey: 'logo', removeKey: 'remove_logo', wide: true },
      { key: 'seo_title', label: 'SEO title', type: 'text', maxLength: 190 },
      { key: 'seo_description', label: 'SEO description', type: 'text', maxLength: 500 },
      { key: 'is_active', label: 'Active', type: 'checkbox', default: true },
      { key: 'is_featured', label: 'Featured on homepage', type: 'checkbox' },
    ],
    deleteMessage: (r) => `“${r['name']}” will be removed. Brands with products cannot be deleted — deactivate them instead.`,
  },

  manufacturers: {
    key: 'manufacturers',
    title: 'Vehicle manufacturers',
    subtitle: 'Makes shown in the vehicle selector (Maruti Suzuki, Hyundai, Honda…).',
    singular: 'Manufacturer',
    resource: 'vehicles/manufacturers',
    paginated: false,
    multipart: true,
    toggle: 'is_active',
    refreshesLookups: true,
    rowTitle: (r) => r['name'],
    filters: [{ key: 'vehicle_type', label: 'Types', options: [...vehicleTypes, { value: 'both', label: 'Both' }] }],
    columns: [
      { key: 'logo', label: '', type: 'image' },
      { key: 'name', label: 'Manufacturer', type: 'strong', sub: (r) => r['country'] },
      { key: 'vehicle_type', label: 'Type', value: (r) => humanize(r['vehicle_type']) },
      { key: 'models_count', label: 'Models', type: 'number', align: 'right' },
      { key: 'is_active', label: 'Active', type: 'toggle' },
    ],
    links: [{ label: 'Models', path: () => ['/admin/vehicles/models'], query: (r) => ({ manufacturer_id: r['id'] }) }],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, maxLength: 100 },
      { key: 'vehicle_type', label: 'Makes', type: 'select', required: true, options: [...vehicleTypes, { value: 'both', label: 'Cars & motorcycles' }] },
      { key: 'country', label: 'Country', type: 'text', maxLength: 60 },
      { key: 'sort_order', label: 'Sort order', type: 'number', min: 0, default: 0 },
      { key: 'logo', label: 'Logo', type: 'image', imageKey: 'logo', wide: true },
      { key: 'is_active', label: 'Active', type: 'checkbox', default: true },
    ],
    deleteMessage: (r) => `“${r['name']}” and all its models and variants will be removed. Manufacturers linked to product compatibility cannot be deleted.`,
  },

  models: {
    key: 'models',
    title: 'Vehicle models',
    subtitle: 'Models per manufacturer (Swift, Creta, Activa…).',
    singular: 'Model',
    resource: 'vehicles/models',
    paginated: false,
    toggle: 'is_active',
    rowTitle: (r) => `${r['manufacturer']?.name ?? ''} ${r['name']}`,
    filters: [{ key: 'manufacturer_id', label: 'Manufacturers', options: manufacturerOptions }],
    columns: [
      { key: 'name', label: 'Model', type: 'strong', sub: (r) => r['manufacturer']?.name },
      { key: 'vehicle_type', label: 'Type', value: (r) => humanize(r['vehicle_type']) },
      { key: 'body_type', label: 'Body', hideMobile: true },
      { key: 'variants_count', label: 'Variants', type: 'number', align: 'right' },
      { key: 'is_active', label: 'Active', type: 'toggle' },
    ],
    links: [{ label: 'Variants', path: () => ['/admin/vehicles/variants'], query: (r) => ({ model_id: r['id'] }) }],
    fields: [
      { key: 'vehicle_manufacturer_id', label: 'Manufacturer', type: 'select', required: true, options: manufacturerOptions },
      { key: 'name', label: 'Model name', type: 'text', required: true, maxLength: 100 },
      { key: 'vehicle_type', label: 'Vehicle type', type: 'select', required: true, options: vehicleTypes },
      { key: 'body_type', label: 'Body type', type: 'text', maxLength: 40, placeholder: 'Hatchback, SUV, Scooter…' },
      { key: 'is_active', label: 'Active', type: 'checkbox', default: true },
    ],
  },

  variants: {
    key: 'variants',
    title: 'Vehicle variants',
    subtitle: 'Engine / year / transmission variants used for exact fitment.',
    singular: 'Variant',
    resource: 'vehicles/variants',
    paginated: false,
    toggle: 'is_active',
    rowTitle: (r) => r['full_name'] ?? r['name'],
    search: false,
    filters: [
      { key: 'manufacturer_id', label: 'Manufacturers', options: manufacturerOptions },
      { key: 'model_id', label: 'Models', options: (ctx) => ctx.async['models'] ?? [] },
    ],
    asyncOptions: {
      models: (api) => api.get<AdminModel[]>('vehicles/models').pipe(map((rows) => rows.map((m) => ({ value: m.id, label: `${m.manufacturer?.name ?? ''} ${m.name}`.trim(), group: m.manufacturer?.name })))),
    },
    columns: [
      { key: 'name', label: 'Variant', type: 'strong', sub: (r) => `${r['model']?.manufacturer?.name ?? ''} ${r['model']?.name ?? ''}` },
      { key: 'year_range', label: 'Years' },
      { key: 'engine', label: 'Engine', hideMobile: true },
      { key: 'fuel_type', label: 'Fuel', hideMobile: true },
      { key: 'transmission', label: 'Gearbox', hideMobile: true },
      { key: 'is_active', label: 'Active', type: 'toggle' },
    ],
    fields: [
      { key: 'vehicle_model_id', label: 'Model', type: 'select', required: true, options: (ctx) => ctx.async['models'] ?? [], full: true },
      { key: 'name', label: 'Variant name', type: 'text', required: true, maxLength: 120, placeholder: 'e.g. 1.2 VXi' },
      { key: 'engine', label: 'Engine', type: 'text', maxLength: 100, placeholder: 'e.g. 1.2L K-Series' },
      { key: 'year_from', label: 'Year from', type: 'number', required: true, min: 1950, max: new Date().getFullYear() + 2 },
      { key: 'year_to', label: 'Year to', type: 'number', min: 1950, max: new Date().getFullYear() + 2, hint: 'Leave blank if still in production.' },
      { key: 'fuel_type', label: 'Fuel', type: 'select', options: (ctx) => (ctx.lookups?.fuel_types ?? []).map((f) => ({ value: f, label: f })) },
      { key: 'transmission', label: 'Transmission', type: 'select', options: (ctx) => (ctx.lookups?.transmissions ?? []).map((f) => ({ value: f, label: f })) },
      { key: 'displacement_cc', label: 'Displacement (cc)', type: 'number', min: 0, max: 10000 },
      { key: 'is_active', label: 'Active', type: 'checkbox', default: true },
    ],
  },

  attributes: {
    key: 'attributes',
    title: 'Product attributes',
    subtitle: 'Filterable attributes (colour, material, viscosity…) and their allowed values.',
    singular: 'Attribute',
    resource: 'attributes',
    paginated: false,
    search: false,
    updateMethod: 'put',
    refreshesLookups: true,
    rowTitle: (r) => r['name'],
    columns: [
      { key: 'name', label: 'Attribute', type: 'strong' },
      { key: 'values', label: 'Values', value: (r) => (r['values'] as { value: string }[]).map((v) => v.value).join(', ') },
      { key: 'is_filterable', label: 'Filterable', type: 'bool' },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, maxLength: 100 },
      { key: 'is_filterable', label: 'Show as storefront filter', type: 'checkbox', default: true },
      { key: 'values', label: 'Values', type: 'tags', placeholder: 'Add a value and press Enter' },
    ],
    fromRow: (r) => ({ ...r, values: (r['values'] as { value: string }[]).map((v) => v.value) }),
  },

  coupons: {
    key: 'coupons',
    title: 'Coupons',
    subtitle: 'Discount codes. Laravel re-validates every coupon at checkout.',
    singular: 'Coupon',
    resource: 'coupons',
    toggle: 'is_active',
    rowTitle: (r) => r['code'],
    filters: [{ key: 'status', label: 'Statuses', options: [{ value: 'active', label: 'Currently valid' }, { value: 'inactive', label: 'Disabled' }, { value: 'expired', label: 'Expired' }] }],
    columns: [
      { key: 'code', label: 'Code', type: 'code' },
      { key: 'name', label: 'Name', type: 'strong', sub: (r) => r['description'] },
      { key: 'type_label', label: 'Discount', value: (r) => (r['type'] === 'percentage' ? `${r['value']}% off` : r['type'] === 'fixed' ? `₹${r['value']} off` : 'Free shipping'), sub: (r) => (r['min_order_amount'] ? `Min. ₹${r['min_order_amount']}` : null) },
      { key: 'used_count', label: 'Used', align: 'right', value: (r) => `${r['used_count']}${r['usage_limit'] ? ' / ' + r['usage_limit'] : ''}` },
      { key: 'expires_at', label: 'Expires', type: 'date', sub: (r) => (r['is_expired'] ? 'Expired' : null), hideMobile: true },
      { key: 'is_active', label: 'Active', type: 'toggle' },
    ],
    fields: [
      { key: 'code', label: 'Code', type: 'text', required: true, maxLength: 40, uppercase: true, pattern: /^[A-Za-z0-9_-]+$/, patternMessage: 'Letters, numbers, dash and underscore only.' },
      { key: 'name', label: 'Name', type: 'text', required: true, maxLength: 120 },
      { key: 'description', label: 'Description', type: 'text', maxLength: 255, full: true },
      { key: 'type', label: 'Type', type: 'select', required: true, default: 'percentage', options: [{ value: 'percentage', label: 'Percentage off' }, { value: 'fixed', label: 'Fixed amount off' }, { value: 'free_shipping', label: 'Free shipping' }] },
      { key: 'value', label: 'Value', type: 'number', min: 0, step: 0.01, visible: (v) => v['type'] !== 'free_shipping', hint: '% for percentage, ₹ for fixed amount' },
      { key: 'min_order_amount', label: 'Minimum order (₹)', type: 'number', min: 0, default: 0 },
      { key: 'max_discount', label: 'Maximum discount (₹)', type: 'number', min: 0, visible: (v) => v['type'] === 'percentage', hint: 'Caps percentage discounts.' },
      { key: 'starts_at', label: 'Starts', type: 'datetime' },
      { key: 'expires_at', label: 'Expires', type: 'datetime' },
      { key: 'usage_limit', label: 'Total uses', type: 'number', min: 1, hint: 'Blank = unlimited' },
      { key: 'per_user_limit', label: 'Uses per customer', type: 'number', min: 1, hint: 'Blank = unlimited' },
      { key: 'category_ids', label: 'Only for categories', type: 'multiselect', options: (ctx) => categoryOptions(ctx.lookups), hint: 'Leave empty to apply to all categories.' },
      { key: 'product_ids', label: 'Only for products', type: 'products', hint: 'Leave empty to apply to all products.' },
      { key: 'is_active', label: 'Active', type: 'checkbox', default: true },
    ],
    fromRow: (r) => ({ ...r, product_ids: (r['products'] ?? []).map((p: Row) => ({ id: p['id'], name: p['name'], sku: p['sku'] })), category_ids: r['category_ids'] ?? [] }),
    toPayload: (v) => ({ ...v, value: v['type'] === 'free_shipping' ? 0 : v['value'], max_discount: v['type'] === 'percentage' ? v['max_discount'] : null }),
  },

  banners: {
    key: 'banners',
    title: 'Banners',
    subtitle: 'Homepage hero slides, promo tiles and offer strips.',
    singular: 'Banner',
    resource: 'banners',
    multipart: true,
    toggle: 'is_active',
    search: false,
    rowTitle: (r) => r['title'],
    filters: [{ key: 'placement', label: 'Placements', options: [{ value: 'hero', label: 'Hero slider' }, { value: 'promo', label: 'Promo tiles' }, { value: 'offer', label: 'Offer strip' }] }],
    columns: [
      { key: 'desktop_image', label: '', type: 'image' },
      { key: 'title', label: 'Title', type: 'strong', sub: (r) => r['subtitle'] },
      { key: 'placement', label: 'Placement', value: (r) => humanize(r['placement']) },
      { key: 'cta_url', label: 'Link', hideMobile: true },
      { key: 'ends_at', label: 'Ends', type: 'date', hideMobile: true },
      { key: 'sort_order', label: 'Order', type: 'number', align: 'right' },
      { key: 'is_active', label: 'Active', type: 'toggle' },
    ],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true, maxLength: 190, full: true },
      { key: 'eyebrow', label: 'Eyebrow', type: 'text', maxLength: 80, placeholder: 'e.g. Monsoon sale' },
      { key: 'subtitle', label: 'Subtitle', type: 'text', maxLength: 255 },
      { key: 'cta_label', label: 'Button label', type: 'text', maxLength: 60 },
      { key: 'cta_url', label: 'Button link', type: 'text', maxLength: 255, placeholder: '/shop or https://…', pattern: /^(\/|https?:\/\/)/, patternMessage: 'Must start with / or http(s)://' },
      { key: 'placement', label: 'Placement', type: 'select', required: true, default: 'hero', options: [{ value: 'hero', label: 'Hero slider' }, { value: 'promo', label: 'Promo tile' }, { value: 'offer', label: 'Offer strip' }] },
      { key: 'theme', label: 'Text colour', type: 'select', required: true, default: 'dark', options: [{ value: 'dark', label: 'Light text on dark image' }, { value: 'light', label: 'Dark text on light image' }] },
      { key: 'starts_at', label: 'Show from', type: 'datetime' },
      { key: 'ends_at', label: 'Show until', type: 'datetime' },
      { key: 'sort_order', label: 'Sort order', type: 'number', min: 0, default: 0 },
      { key: 'is_active', label: 'Active', type: 'checkbox', default: true },
      { key: 'desktop_image', label: 'Desktop image (1600×600 recommended)', type: 'image', imageKey: 'desktop_image', wide: true },
      { key: 'mobile_image', label: 'Mobile image (800×800 recommended)', type: 'image', imageKey: 'mobile_image' },
    ],
  },

  pages: {
    key: 'pages',
    title: 'Pages',
    subtitle: 'About, terms, privacy, shipping and returns policies.',
    singular: 'Page',
    resource: 'pages',
    toggle: 'is_active',
    modalSize: 'xl',
    rowTitle: (r) => r['title'],
    columns: [
      { key: 'title', label: 'Title', type: 'strong', sub: (r) => `/page/${r['slug']}` },
      { key: 'updated_at', label: 'Updated', type: 'datetime' },
      { key: 'is_active', label: 'Published', type: 'toggle' },
    ],
    links: [{ label: 'View', path: (r) => ['/page', r['slug']] }],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true, maxLength: 190 },
      { key: 'slug', label: 'Slug', type: 'text', maxLength: 190, hint: 'URL: /page/<slug>. Blank = from title.' },
      { key: 'content', label: 'Content (HTML)', type: 'html', required: true, rows: 16, hint: 'Scripts and unsafe attributes are stripped when displayed.' },
      { key: 'meta_title', label: 'Meta title', type: 'text', maxLength: 190 },
      { key: 'meta_description', label: 'Meta description', type: 'text', maxLength: 500 },
      { key: 'is_active', label: 'Published', type: 'checkbox', default: true },
    ],
  },

  faqs: {
    key: 'faqs',
    title: 'FAQs',
    subtitle: 'Questions shown on the FAQ page, grouped by category.',
    singular: 'FAQ',
    resource: 'faqs',
    toggle: 'is_active',
    perPage: 50,
    rowTitle: (r) => r['question'],
    columns: [
      { key: 'question', label: 'Question', type: 'strong', sub: (r) => r['category'] },
      { key: 'sort_order', label: 'Order', type: 'number', align: 'right' },
      { key: 'is_active', label: 'Active', type: 'toggle' },
    ],
    fields: [
      { key: 'category', label: 'Category', type: 'text', required: true, maxLength: 60, placeholder: 'Orders & shipping' },
      { key: 'sort_order', label: 'Sort order', type: 'number', min: 0, default: 0 },
      { key: 'question', label: 'Question', type: 'text', required: true, maxLength: 255, full: true },
      { key: 'answer', label: 'Answer', type: 'textarea', required: true, maxLength: 5000, rows: 5 },
      { key: 'is_active', label: 'Active', type: 'checkbox', default: true },
    ],
  },

  blog: {
    key: 'blog',
    title: 'Blog posts',
    subtitle: 'Guides and articles for the Garage notes blog.',
    singular: 'Post',
    resource: 'blog',
    multipart: true,
    modalSize: 'xl',
    rowTitle: (r) => r['title'],
    filters: [{ key: 'status', label: 'Statuses', options: [{ value: 'published', label: 'Published' }, { value: 'draft', label: 'Draft' }] }],
    asyncOptions: {
      blogCategories: (api) => api.page<{ id: number; name: string }>('blog-categories', { per_page: 100 }).pipe(map((p) => p.items.map((c) => ({ value: c.id, label: c.name })))),
    },
    columns: [
      { key: 'cover_image', label: '', type: 'image' },
      { key: 'title', label: 'Title', type: 'strong', sub: (r) => r['category']?.name },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'author', label: 'Author', hideMobile: true },
      { key: 'published_at', label: 'Published', type: 'date', hideMobile: true },
    ],
    links: [{ label: 'View', path: (r) => ['/blog', r['slug']] }],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true, maxLength: 190, full: true },
      { key: 'slug', label: 'Slug', type: 'text', maxLength: 190, hint: 'Blank = from title.' },
      { key: 'blog_category_id', label: 'Category', type: 'select', options: (ctx) => ctx.async['blogCategories'] ?? [] },
      { key: 'status', label: 'Status', type: 'select', required: true, default: 'draft', options: [{ value: 'draft', label: 'Draft' }, { value: 'published', label: 'Published' }] },
      { key: 'published_at', label: 'Publish date', type: 'datetime', hint: 'Blank = now when published.' },
      { key: 'excerpt', label: 'Excerpt', type: 'textarea', maxLength: 500, rows: 2 },
      { key: 'content', label: 'Content (HTML)', type: 'html', required: true, rows: 14 },
      { key: 'cover_image', label: 'Cover image', type: 'image', imageKey: 'cover_image', wide: true },
      { key: 'tags', label: 'Tags', type: 'tags', placeholder: 'maintenance, brakes…' },
      { key: 'meta_title', label: 'Meta title', type: 'text', maxLength: 190 },
      { key: 'meta_description', label: 'Meta description', type: 'text', maxLength: 500 },
    ],
    fromRow: (r) => ({ ...r, tags: (r['tags'] ?? []).map((t: Row) => t['name']) }),
  },

  'blog-categories': {
    key: 'blog-categories',
    title: 'Blog categories',
    singular: 'Blog category',
    resource: 'blog-categories',
    rowTitle: (r) => r['name'],
    columns: [
      { key: 'name', label: 'Name', type: 'strong', sub: (r) => r['slug'] },
      { key: 'description', label: 'Description', hideMobile: true },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, maxLength: 100 },
      { key: 'slug', label: 'Slug', type: 'text', maxLength: 120 },
      { key: 'description', label: 'Description', type: 'text', maxLength: 255, full: true },
    ],
  },

  testimonials: {
    key: 'testimonials',
    title: 'Testimonials',
    subtitle: 'Customer quotes shown on the homepage.',
    singular: 'Testimonial',
    resource: 'testimonials',
    toggle: 'is_active',
    rowTitle: (r) => r['name'],
    columns: [
      { key: 'name', label: 'Customer', type: 'strong', sub: (r) => [r['location'], r['vehicle']].filter(Boolean).join(' · ') },
      { key: 'content', label: 'Quote', value: (r) => (r['content'] as string).slice(0, 90) + ((r['content'] as string).length > 90 ? '…' : ''), hideMobile: true },
      { key: 'rating', label: 'Rating', type: 'rating' },
      { key: 'is_active', label: 'Active', type: 'toggle' },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, maxLength: 100 },
      { key: 'location', label: 'City', type: 'text', maxLength: 100 },
      { key: 'vehicle', label: 'Vehicle', type: 'text', maxLength: 100, placeholder: 'e.g. Hyundai Creta' },
      { key: 'rating', label: 'Rating', type: 'rating', default: 5 },
      { key: 'content', label: 'Quote', type: 'textarea', required: true, maxLength: 1000 },
      { key: 'sort_order', label: 'Sort order', type: 'number', min: 0, default: 0 },
      { key: 'is_active', label: 'Active', type: 'checkbox', default: true },
    ],
  },

  enquiries: {
    key: 'enquiries',
    title: 'Contact enquiries',
    subtitle: 'Messages from the contact form.',
    singular: 'Enquiry',
    resource: 'contact-messages',
    create: false,
    rowTitle: (r) => r['subject'],
    filters: [{ key: 'status', label: 'Statuses', options: ['new', 'read', 'replied', 'closed'].map((s) => ({ value: s, label: humanize(s) })) }],
    columns: [
      { key: 'subject', label: 'Subject', type: 'strong', sub: (r) => `${r['name']} · ${r['email']}` },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'created_at', label: 'Received', type: 'datetime' },
    ],
    fields: [
      { key: 'from', label: 'From', type: 'readonly', render: (r) => `${r['name']} <${r['email']}>${r['phone'] ? ' · ' + r['phone'] : ''}` },
      { key: 'subject_ro', label: 'Subject', type: 'readonly', render: (r) => r['subject'] },
      { key: 'message', label: 'Message', type: 'readonly', full: true, render: (r) => r['message'] },
      { key: 'status', label: 'Status', type: 'select', required: true, options: ['new', 'read', 'replied', 'closed'].map((s) => ({ value: s, label: humanize(s) })) },
      { key: 'admin_notes', label: 'Internal notes', type: 'textarea', maxLength: 2000, rows: 3 },
    ],
    toPayload: (v) => ({ status: v['status'], admin_notes: v['admin_notes'] }),
  },

  newsletter: {
    key: 'newsletter',
    title: 'Newsletter subscribers',
    singular: 'Subscriber',
    resource: 'newsletter-subscribers',
    rowTitle: (r) => r['email'],
    exportFile: { path: 'newsletter-subscribers/export', filename: 'newsletter-subscribers.csv' },
    filters: [{ key: 'status', label: 'Statuses', options: [{ value: 'subscribed', label: 'Subscribed' }, { value: 'unsubscribed', label: 'Unsubscribed' }] }],
    columns: [
      { key: 'email', label: 'Email', type: 'strong' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'source', label: 'Source', hideMobile: true },
      { key: 'created_at', label: 'Subscribed', type: 'date' },
    ],
    fields: [
      { key: 'email', label: 'Email', type: 'email', required: true, maxLength: 190 },
      { key: 'status', label: 'Status', type: 'select', required: true, default: 'subscribed', options: [{ value: 'subscribed', label: 'Subscribed' }, { value: 'unsubscribed', label: 'Unsubscribed' }] },
      { key: 'source', label: 'Source', type: 'text', maxLength: 40, default: 'admin' },
    ],
  },

  staff: {
    key: 'staff',
    title: 'Staff users',
    subtitle: 'Admin panel accounts. Permissions come from roles.',
    singular: 'Staff user',
    resource: 'staff',
    toggle: 'is_active',
    rowTitle: (r) => r['name'],
    asyncOptions: {
      roles: (api) => api.get<{ roles: RoleRow[] }>('roles').pipe(map((r) => r.roles.filter((x) => x.is_staff).map((x) => ({ value: x.name, label: x.label })))),
    },
    columns: [
      { key: 'name', label: 'Name', type: 'strong', sub: (r) => r['email'] },
      { key: 'roles', label: 'Roles', value: (r) => (r['roles'] as { label: string }[]).map((x) => x.label).join(', ') },
      { key: 'last_login_at', label: 'Last login', type: 'datetime', hideMobile: true },
      { key: 'is_active', label: 'Active', type: 'toggle' },
    ],
    fields: [
      { key: 'name', label: 'Full name', type: 'text', required: true, maxLength: 100 },
      { key: 'email', label: 'Email', type: 'email', required: true, maxLength: 190 },
      { key: 'phone', label: 'Phone', type: 'text', maxLength: 20 },
      { key: 'password', label: 'Password', type: 'password', requiredOnCreate: true, hint: 'Min. 8 characters with letters and numbers. Leave blank to keep the current password.' },
      { key: 'roles', label: 'Roles', type: 'multiselect', required: true, options: (ctx) => ctx.async['roles'] ?? [] },
      { key: 'is_active', label: 'Active (can sign in)', type: 'checkbox', default: true },
    ],
    fromRow: (r) => ({ ...r, password: '', roles: (r['roles'] as { name: string }[]).map((x) => x.name) }),
    deleteMessage: (r) => `${r['name']} will lose access to the admin panel immediately.`,
  },

  'audit-logs': {
    key: 'audit-logs',
    title: 'Audit log',
    subtitle: 'Every admin change is recorded with who, what and when.',
    singular: 'Audit entry',
    resource: 'audit-logs',
    create: false,
    remove: false,
    readOnly: true,
    perPage: 30,
    search: false,
    rowTitle: (r) => r['action'],
    filters: [
      {
        key: 'action',
        label: 'Actions',
        options: ['product', 'order', 'inventory', 'coupon', 'category', 'brand', 'review', 'settings', 'staff', 'customer', 'banner', 'blog'].map((a) => ({ value: a, label: humanize(a) })),
      },
    ],
    columns: [
      { key: 'created_at', label: 'When', type: 'datetime' },
      { key: 'user', label: 'User', value: (r) => r['user']?.name ?? 'System' },
      { key: 'action', label: 'Action', type: 'code' },
      { key: 'subject', label: 'Subject', value: (r) => (r['subject_type'] ? `${String(r['subject_type']).split('\\').pop()} #${r['subject_id']}` : '—'), hideMobile: true },
      { key: 'ip_address', label: 'IP', hideMobile: true },
    ],
    fields: [
      { key: 'who', label: 'User', type: 'readonly', render: (r) => `${r['user']?.name ?? 'System'} · ${r['ip_address'] ?? ''}` },
      { key: 'what', label: 'Action', type: 'readonly', render: (r) => r['action'] },
      { key: 'old', label: 'Before', type: 'readonly', full: true, render: (r) => json(r['old_values']) },
      { key: 'new', label: 'After', type: 'readonly', full: true, render: (r) => json(r['new_values']) },
    ],
  },
};
